#!/bin/sh
# Build akane-injector + libakane-runtime.so. First embeds each built
# out/module/*/akane.ko as a .incbin'd .S blob plus a module_blobs_table.c,
# then runs ndk-build.
set -e

OUT="$1"
ABI="${2:-arm64-v8a}"
if [ -z "$OUT" ]; then
	echo "usage: $0 <out-dir> [abi]" >&2
	exit 2
fi

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INJECTOR_DIR="$PROJECT_ROOT/injector"
BLOBS_DIR="$OUT/injector/blobs"

# Default Android SDK location differs between macOS and Linux.
case "$(uname -s)" in
	Darwin) DEFAULT_SDK="$HOME/Library/Android/sdk" ;;
	*)      DEFAULT_SDK="$HOME/Android/Sdk" ;;
esac

SDK="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-$DEFAULT_SDK}}"
NDK="${ANDROID_NDK_HOME:-$SDK/ndk/26.3.11579264}"

# ---------- gather built kernel modules ----------
mkdir -p "$BLOBS_DIR"

# Each entry is "<label>:<abs-path>" so we keep both pieces together.
ENTRIES=""
if [ -d "$OUT/module" ]; then
	for dir in "$OUT/module"/*/; do
		[ -d "$dir" ] || continue
		label="$(basename "$dir")"
		ko="$dir/akane.ko"
		if [ -f "$ko" ]; then
			ENTRIES="$ENTRIES $label:$ko"
		fi
	done
fi

if [ -z "$ENTRIES" ]; then
	echo "no .ko artifacts found under $OUT/module" >&2
	echo "run 'make module' first (and check the docker build logs)" >&2
	exit 1
fi

# ---------- generate blob_<sanitized>.S + table.c ----------
TABLE_C="$BLOBS_DIR/module_blobs_table.c"
SOURCES_MK="$BLOBS_DIR/sources.mk"

# C identifier: replace . and - with _ in the kernel label.
sanitize() { echo "$1" | tr '.-' '__'; }

# Parse "androidNN-X.Y" into the three integers needed for matching.
parse_label() {
	# $1 = "android12-5.10"; sets $ANDROID $KMAJ $KMIN
	ANDROID=$(echo "$1" | sed -n 's/^android\([0-9]*\)-.*/\1/p')
	KMAJ=$(echo    "$1" | sed -n 's/^android[0-9]*-\([0-9]*\)\..*/\1/p')
	KMIN=$(echo    "$1" | sed -n 's/^android[0-9]*-[0-9]*\.\([0-9]*\).*/\1/p')
}

{
	echo "/* Generated by scripts/build-injector.sh. Do not edit. */"
	echo "#include \"module_blobs.h\""
	echo
} > "$TABLE_C"

BLOB_S_FILES=""
for entry in $ENTRIES; do
	label="${entry%%:*}"
	ko_path="${entry#*:}"
	sym="$(sanitize "$label")"
	parse_label "$label"

	blob_s="$BLOBS_DIR/blob_${sym}.S"
	cat > "$blob_s" <<EOF
/* Generated. Embeds out/module/${label}/akane.ko. */
.section .rodata.akane_ko_${sym}, "a"
.balign 8
.global akane_ko_${sym}_start
.global akane_ko_${sym}_end

akane_ko_${sym}_start:
.incbin "${ko_path}"
akane_ko_${sym}_end:

.section .note.GNU-stack, "", %progbits
EOF
	BLOB_S_FILES="$BLOB_S_FILES $blob_s"

	{
		echo "extern const unsigned char akane_ko_${sym}_start[];"
		echo "extern const unsigned char akane_ko_${sym}_end[];"
	} >> "$TABLE_C"
done

{
	echo
	echo "const struct akane_ko_blob akane_ko_blobs[] = {"
	for entry in $ENTRIES; do
		label="${entry%%:*}"
		sym="$(sanitize "$label")"
		parse_label "$label"
		printf '\t{ "%s", %s, %s, %s, akane_ko_%s_start, akane_ko_%s_end },\n' \
			"$label" "$ANDROID" "$KMAJ" "$KMIN" "$sym" "$sym"
	done
	echo "};"
	echo "const unsigned akane_ko_blob_count ="
	echo "    sizeof(akane_ko_blobs) / sizeof(akane_ko_blobs[0]);"
} >> "$TABLE_C"

# sources.mk lists everything the controller/Android.mk needs to add to
# LOCAL_SRC_FILES. Absolute paths are accepted by ndk-build.
{
	echo "# Generated by scripts/build-injector.sh."
	printf 'AKANE_BLOB_SRCS :='
	for f in $BLOB_S_FILES; do printf ' \\\n    %s' "$f"; done
	printf ' \\\n    %s\n' "$TABLE_C"
} > "$SOURCES_MK"

echo "embedding $(echo "$ENTRIES" | wc -w | tr -d ' ') kernel variant(s):"
for entry in $ENTRIES; do
	echo "  - ${entry%%:*}"
done

# ---------- ndk-build ----------
"$NDK/ndk-build"                                       \
	NDK_PROJECT_PATH=null                          \
	APP_BUILD_SCRIPT="$INJECTOR_DIR/Android.mk"    \
	NDK_APPLICATION_MK="$INJECTOR_DIR/Application.mk" \
	NDK_OUT="$OUT/injector/obj"                    \
	NDK_LIBS_OUT="$OUT/injector/libs"              \
	BLOBS_DIR="$BLOBS_DIR"                         \
	APP_ABI="$ABI"

echo "built $OUT/injector/libs/$ABI/{akane-injector,libakane-runtime.so}"
